package com.ruvla.plsos.agg.model;

/**
 * @author Vladislav
 * Class to introduce exception that can be used for detecting exceptions generated by Plsos system.
 */
@SuppressWarnings("serial")
public class PlsosException extends Exception {

	public PlsosException(String string) {
		super(string);
	}

}
